// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.LayoutNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("orgchart_layout", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "parent",
                            Role = "Board"
                        },
                        new
                        {
                            Id = "1",
                            ParentId = "parent",
                            Role = "General Manager"
                        },
                        new
                        {
                            Id = "2",
                            ParentId = "1",
                            Role = "Human Resource Manager"
                        },
                        new
                        {
                            Id = "3",
                            ParentId = "2",
                            Role = "Trainers"
                        },
                        new
                        {
                            Id = "4",
                            ParentId = "2",
                            Role = "Recruiting Team"
                        },
                        new
                        {
                            Id = "5",
                            ParentId = "2",
                            Role = "Finance Asst. Manager"
                        },
                        new
                        {
                            Id = "6",
                            ParentId = "1",
                            Role = "Design Manager"
                        },
                        new
                        {
                            Id = "7",
                            ParentId = "6",
                            Role = "Design Supervisor"
                        },
                        new
                        {
                            Id = "8",
                            ParentId = "6",
                            Role = "Development Supervisor"
                        },
                        new
                        {
                            Id = "9",
                            ParentId = "6",
                            Role = "Drafting Supervisor"
                        },
                        new
                        {
                            Id = "10",
                            ParentId = "1",
                            Role = "Operations Manager"
                        },
                        new
                        {
                            Id = "11",
                            ParentId = "10",
                            Role = "Statistics Department"
                        },
                        new
                        {
                            Id = "12",
                            ParentId = "10",
                            Role = "Logistics Department"
                        },
                        new
                        {
                            Id = "16",
                            ParentId = "1",
                            Role = "Marketing Manager"
                        },
                        new
                        {
                            Id = "17",
                            ParentId = "16",
                            Role = "Overseas Sales Manager"
                        },
                        new
                        {
                            Id = "18",
                            ParentId = "16",
                            Role = "Petroleum Manager"
                        },
                        new
                        {
                            Id = "20",
                            ParentId = "16",
                            Role = "Service Department Manager"
                        },
                        new
                        {
                            Id = "21",
                            ParentId = "16",
                            Role = "Quality Control Department"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
